# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['taskmover\\__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('settings.yml', '.'),
        ('taskmover\\ui\\docs', 'taskmover\\ui\\docs'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'yaml',
        'taskmover',
        'taskmover.ui',
        'taskmover.ui.theme_manager',
        'taskmover.ui.input_components',
        'taskmover.ui.display_components',
        'taskmover.ui.layout_components',
        'taskmover.ui.navigation_components',
        'taskmover.ui.data_display_components',
        'taskmover.ui.dialog_components',
        'taskmover.ui.pattern_management_components',
        'taskmover.ui.rule_management_components',
        'taskmover.ui.ruleset_management_components',
        'taskmover.ui.file_organization_components',
        'taskmover.ui.advanced_ui_features',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='TaskMover',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='build\\version_info.txt',
)
